#name, main, version and api are required
name: Ghosty
main: net.easecation.ghosty.GhostyPlugin
#remember version and api is string, don'JsonPacket write it like this: 1.0.0, or there will be an exception
version: "0.0.1"
api: ["1.0.0"]

load: STARTUP
author: EaseCation Team
description: Ghosty - Record player moves and playback when server is empty - like walking ghosts
website: http://easecation.net